"""add_favorite_movie

Revision ID: 8ae88b06a183
Revises: 4b3bbe69293b
Create Date: 2019-06-29 19:43:46.419885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae88b06a183'
down_revision = '4b3bbe69293b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_movie',
    sa.Column('_created_at', sa.DateTime(), nullable=False),
    sa.Column('_updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('imdb_movie_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorite_movie_imdb_movie_id'), 'favorite_movie', ['imdb_movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_movie_imdb_movie_id'), table_name='favorite_movie')
    op.drop_table('favorite_movie')
    # ### end Alembic commands ###
