"""empty message

Revision ID: 8cd66db00e43
Revises: 9d2a76c3a2a1
Create Date: 2019-07-08 19:27:55.781343

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8cd66db00e43'
down_revision = '9d2a76c3a2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_movie', sa.Column('imdb_id', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_favorite_movie_imdb_id'), 'favorite_movie', ['imdb_id'], unique=False)
    op.drop_index('ix_favorite_movie_imdb_movie_id', table_name='favorite_movie')
    op.drop_column('favorite_movie', 'imdb_movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_movie',
                  sa.Column('imdb_movie_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_index('ix_favorite_movie_imdb_movie_id', 'favorite_movie', ['imdb_movie_id'], unique=False)
    op.drop_index(op.f('ix_favorite_movie_imdb_id'), table_name='favorite_movie')
    op.drop_column('favorite_movie', 'imdb_id')
    # ### end Alembic commands ###
