"""empty message

Revision ID: 9d2a76c3a2a1
Revises: 8ae88b06a183
Create Date: 2019-07-08 17:45:27.591448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d2a76c3a2a1'
down_revision = '8ae88b06a183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite_movie', '_updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('user', '_updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', '_updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('favorite_movie', '_updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    # ### end Alembic commands ###
